apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    name: myapp-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-pod
  template:
    metadata:
      labels:
        name:myapp-pod
      spec:
        containers:
          - name: nginx
            image: nginx
            ports:
              - containerPort: 80