pipeline{
    agent any
        tools {
            maven 'Maven'
            jdk 'Java_11'
        }
    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/sharath050175/DevOps.git'
            }
        }
        stage('Maven clean'){
            steps{
                sh 'mvn clean'
            }
        }        
        stage('Maven Build'){
            steps{
                sh 'mvn clean install'
            }
        }    
    }
}    