pipeline{
    agent any
    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/sharath050175/DevOps.git'
            }
        }
        stage('Build'){
            steps{
                echo 'Building the project.'
            }
        }        
        stage('Deploy'){
            steps{
                echo 'Deploy the Application.'
            }
        }    
    }
}    