apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: app-cm
          key: firstname  # corrected 'keyname' to 'key'
    command: ['sh','-c','echo this app is running..! && sleep 3600']
