apiVersion: v1
kind: Pod
metadata:
  name: memory-test-3
  namespace: mem-testing
spec:
  containers:
  - name: memory-demo
    image: polinux/stress
    resources:
      requests:
        memory: "2G"
      limits:
        memory: "2G"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","150M","--vm-hang","1"]