apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    name: myapp-pod
spec:
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80