pipeline{
    agent {
        label 'prod'
    }

    stages{
        stage('servier-ip'){
            steps{
                sh '''
                    hostname -I
                    echo "Server IP Address: $(hostname -I)"

                '''
            }
        } 
        stage('Uptime'){
            steps{
                sh '''
                    uptime
                    echo 'Server IP Address: $(uptime)'
                '''
            }

        }
    }
}