pipeline {
    agent any

    tools {
        jdk 'java-11'        // must match Global Tool name
        maven 'maven'        // must match Global Tool name
    }

    stages {
        stage('git-checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sharath050175/DevOps.git'
            }
        }    
        stage('compile') {
            steps {
                sh 'mvn compile'
            }
        }    
        stage('maven build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('docker build') {
            steps {
                sh 'docker build -t app .'
                // OR use this if Dockerfile is inside /app
                // sh 'docker build -t app -f app/Dockerfile ./app'
            }
        }
        stage('containerization') {
            steps {
                sh 'docker run -it -d --name c1 -p 9000:8080 app'
            }
        }
        stage('pushing to docker-hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS| docker login -u $USER --password-stdin'
                    sh 'docker tag app sharath/app:v1'
                    sh 'docker push sharath/app:v1'
                }
            }
        }
    }        
}
