pipeline{
    agent any

    tools{
        jdk 'java-11'
        maven 'maven'

    }

    stages{
        stage('git-checkout'){
                steps{
                git branch: 'main', url: 'https://github.com/sharath050175/DevOps.git'
                }
        }    
         stage('compile'){
                steps{
                    sh 'mvn compile'
                }
        }    
         stage('maven build'){
                steps{
                    sh 'mvn clean install'
                }
        }
        stage('docker build'){
                steps{
                    sh 'docker build -t app .'
                }
        }
        stage('containerization'){
                steps{
                    sh 'docker run -it -d --name c1 -p 9000:8080 app'
                }
        }
        stage('pushing to docker-hub'){
                steps{
                    withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker tag app sharusharath/app:v1'
                    sh 'docker push sharusharath/app:v1'
                }
            
        }
    }        
}

      